### ISSUE TITLE
path references and navigation for behat.yml

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-behat-plugin#2]
```
default:
  suites:
    default:
      paths:
        - "%paths.base%/tests/features"
        - "%paths.base%/src/.../FOO.feature"
```
